### ISSUE TITLE
list out of range

### ISSUE THREAD

**Issue by mokems** [SerialLain3170/Colorization#10]
I am sorry I faced this problem when I use the code nohint_pix2pix
   
Colorization\nohint_pix2pix\dataset.py", line 143, in valid
    color_path = self.val_list[index]
IndexError: list index out of range

and I did not know how to solve it

**Comment by SerialLain3170** [comment]
Thank you for your trying.

Judging from IndexError, I suppose that `train.validsize` in `param.yaml` is bigger than `len(self.val_list)`.  Or I assume that the length of `self.pathlist` is too small.  

There are not only stderr but also some logs about your training settings in stdout after running `python train.py --data_path <YOUR DATASET PATH> --sketch_path <YOUR SKETCH PATH>`. Therefore, could you give me all the stdout?

**Comment by SerialLain3170** [comment]
Is the issue fixed ?

**Comment by mokems** [comment]
Yes, the issue has already been solved. Thank you for answering the question. The result was very excellend.
