### ISSUE TITLE
in reference_scft

### ISSUE THREAD

**Issue by Nyoko74** [SerialLain3170/Colorization#11]
While visualizing the validation, the sketch may be superimposed over another sometime.
![QQ截图20210311111917](https://user-images.githubusercontent.com/70626300/110730671-cf827400-825b-11eb-8548-2d8d39b4c10c.jpg)

**Comment by SerialLain3170** [comment]
Thank you for the issue and I am sorry for the inconvenience.

I suppose that file names in your `DATA_PATH` and line arts in `SKETCH_PATH` may not match judging from your visualization results. For example, `SKETCH_PATH/image0.png` must be extracted from `DATA_PATH/image0.png` using SketchKeras. Therefore, could you confirm if file names in `DATA_PATH` and `SKETCH_PATH` match?

**Comment by Nyoko74** [comment]
> Thank you for the issue and I am sorry for the inconvenience.
> 
> I suppose that file names in your `DATA_PATH` and line arts in `SKETCH_PATH` may not match judging from your visualization results. For example, `SKETCH_PATH/image0.png` must be extracted from `DATA_PATH/image0.png` using SketchKeras. Therefore, could you confirm if file names in `DATA_PATH` and `SKETCH_PATH` match?

Yes my `DATA_PATH` and `SKETCH_PATH` does not match, thank you.
