### ISSUE TITLE
License

### ISSUE THREAD

**Issue by EuphoricPenguin** [SerialLain3170/Colorization#16]
I don't see any license mentioned anywhere in the repository, which basically means this entire project is all rights reserved. Please consider adding license information to clarify. If you're unsure, I can't tell you how much I can recommend the permissiveness of the MIT license enough. If you're distributing models, make sure any dependencies aren't in conflict, and consider using something like CC-BY or CC-BY-SA.

**Comment by SerialLain3170** [comment]
Thank you for the issue, and I am very sorry for the late answer.

Since I have wanted everyone to use codes in this repository freely, I do not intend to mention any license. Does this have any problems? Please tell me if problems exist because I do not have any knowledge about license. Thank you in advance.

**Comment by EuphoricPenguin** [comment]
The absence of a license basically means you hold the full copyright. It essentially had the complete opposite effect, legally barring everyone from being able to use your code. I'd suggest the MIT license for the code. It's the right balance of permissiveness with a few restrictions that are sensible. It essentially requires the license to remain with the code to indicate the original creator (in the source code at least). It allows basically everything else though, which is great if that's what you want for your code.

**Comment by SerialLain3170** [comment]
I am very sorry for the late answer.

Thank you for the advice and offering knowledge! As you said, I will set MIT license in the near future!

**Comment by SerialLain3170** [comment]
I set the license. Thank you for teaching me.
