### ISSUE TITLE
How can I resolve such an error ?

### ISSUE THREAD

**Issue by 43tyler** [SerialLain3170/Colorization#23]
Nice to meet you, your code is very helpful!
I apologize for the very personal question.
I used your code "reference_scft" as a reference to do the training.
I have successfully completed the training, but after loading the weight parameters, the following error occurred when I passed the line drawing and reference image as arguments
The code and error are as follows

    gen= Generator()
    self.gen = self._setting_weight( gen , gen_path )

    @staticmethod
    def _setting_weight(model: nn.Module,
                                   weight_path : Dict): 
        model.load_state_dict(torch.load(weight_path))
        model.cuda()
        model.eval()
        return model

    with torch.no_grad():
        y = self.gen(v_list[0],v_list[1]) 

> File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
> TypeError: forward() takes 2 positional arguments but 3 were given

v_list[0] is Line drawing image of tensor ,v_list[1] is reference image of tensor

What should I do to solve this error?

**Comment by SerialLain3170** [comment]
Thank you for the issue.

Is your code inside the class? If not, it seems odd that you use `self`. I think that the following code would work for you.

```py
gen= Generator()
gen = setting_weight( gen , gen_path )

def setting_weight(model: nn.Module,
                               weight_path : Dict): 
    model.load_state_dict(torch.load(weight_path))
    model.cuda()
    model.eval()
    return model

with torch.no_grad():
    y = gen(v_list[0],v_list[1]) 
```

If your code is inside the class, could you paste the overall code you wrote?

**Comment by 43tyler** [comment]
Thanks for the reply.
And sorry for the delay in my reply.
The above code was running inside the "Class Test", but outside the Class, it ran successfully.
I'm not sure why the error occurred inside the Class, but I'm glad it worked.
Thank you very much!

**Comment by SerialLain3170** [comment]
It is good that you could run successfully.

With respect to the reason, I have no idea until I see your overall code.  
If you do not mind, could you paste the entire code?

**Comment by 43tyler** [comment]
Sorry, I didn't save the original code, so I can't reproduce the error code.
I tried again, and now I can run it in "Class Test".
The modified code looks like the following
Is this the correct test code for using the learned weights?
I apologize for any inconvenience caused by my personal problem.

    import yaml
    import torch
    import torch.nn as nn
    import argparse
    from torchvision import transforms as transforms

    from train import Trainer
    from typing import List, Dict
    from pathlib import Path

    from model import Generator, Discriminator
    from PIL import Image
    import datetime

    class Test: 
    def __init__(self,
                          ref_image,
                          line_drawing,
                          outdir):

        self.outdir = outdir
        self.ref_image = ref_image
        self.line_drawing = line_drawing
    
        gen_path = '~'
    
        gen= Generator()
        self.gen = self._setting_weight( gen,gen_path)
    
    @staticmethod
    def _setting_weight(model: nn.Module,
                                       weight_path : Dict):

        model.load_state_dict(torch.load(weight_path))
        model.cuda()
        model.eval()
    
        return model


    @staticmethod
    def transform_image(line_drawing,ref_image):


        ref_image = Image.open(ref_image)
        line_drawing = Image.open(line_drawing)

        totensor = transforms.ToTensor()
    
        ref_image = totensor(ref_image)
        line_drawing = totensor(line_drawing) 
    


        ref_image = ref_image.unsqueeze(0)
        line_drawing = line_drawing.unsqueeze(0)

        return [line_drawing,ref_image]


    def __call__(self):
        v_list= self.transform_image(self.line_drawing,self.ref_image)
        

        v_list[0]= v_list[0].cuda()
        v_list[1] = v_list[1].cuda()
        
        with torch.no_grad():
            y = self.gen(v_list[0],v_list[1]) 

        #transform PIL
        y = y.squeeze()
        PIL = transforms.ToPILImage()
        image = PIL(y)

        #save image
        dt = datetime.datetime.now()
        dt = dt.strftime('%m%d-%H%M')
        image.save(self.outdir + "/" + f"{dt}.jpg")


    if __name__ == "__main__":
        parser = argparse.ArgumentParser(description="Colorization_Test")
        parser.add_argument('--ref_image', type=Path, help="path containing color image")
        parser.add_argument('--line_drawing', type=Path, help="path containing sketch image")
        args = parser.parse_args()

        outdir = '~'
        tester = Test(  args.ref_image,
                                 args.line_drawing,
                                 outdir
                               )

        tester()

**Comment by SerialLain3170** [comment]
I think that the above code seems correct for inference. Thank you
