### ISSUE TITLE
I ran server.py in the program “Adeleine” and got a error:

### ISSUE THREAD

**Issue by zxiangwei** [SerialLain3170/Colorization#24]
I ran server.py in the program “Adeleine” and got a error:
NameError: free variable 'point_infer' referenced before assignment in enclosing scope

it seems that it needs the pretrained file.how could i got this？thank you!

**Comment by zxiangwei** [comment]
sorry,i have downloaded the file point_model.pt,but i met another error when execute`point_infer = PointInferer(str(args.point))`
`TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。`
And when i use vpn.It executes for a long time with no results.
![image](https://user-images.githubusercontent.com/44313751/148666823-2629ca84-1ca8-4cb0-a24c-b49180466eb0.png)

What should i do to solve this problem?

**Comment by SerialLain3170** [comment]
Thank you for the issue.

Actually, I have no idea because I have not experienced running Adeleine on VPN. Does the changing VPN settings make a difference?

**Comment by zxiangwei** [comment]
Thanks for your reply, I found that the program is mostly stuck here:
![image](https://user-images.githubusercontent.com/44313751/148688090-28b56364-52b1-44d0-8a5d-b523a9452db3.png)

And i stumbled upon a problem, when I execute, the following prompt appears, what does this do?
![image](https://user-images.githubusercontent.com/44313751/148688227-bb6abccc-4fe3-4923-a92d-43d0378267aa.png)
![image](https://user-images.githubusercontent.com/44313751/148688878-b0e9de28-9fcb-40b4-b772-bb7e5d9896b0.png)

![image](https://user-images.githubusercontent.com/44313751/148688161-cf72ea67-aa61-48af-94e6-efec568578a5.png)
And i have downloaded this file.Can I avoid downloading it in the program and just use it directly?
Thank you!

**Comment by SerialLain3170** [comment]
I see the problem.

Yes, you can use the pretrained file directly.
In order to do this, you need to call ResNet34 incorporating the pretrained weight in the [line](https://github.com/SerialLain3170/Colorization/blob/master/Adeleine/point/model.py#L163) instead of using `torch.hub`.
When it comes to the original ResNet34, you can refer [this](https://github.com/RF5/danbooru-pretrained/blob/master/danbooru_resnet.py#L98). 

In summary, after you call ResNet34 using above function, you need to give the pretrained weight (you already have downloaded) using `load_state_dict` method like the code below.

```py
class ResNet(nn.Module):
    def __init__(self):
        super(ResNet, self).__init__()
        self.model = resnet34(pretrained=False)
        weight = torch.load(YOUR_PRETRAINED_FILE_PATH)
        self.model.load_state_dict(weight)
        self.model = nn.Sequential(*list(self.model.children())[:-1])
        self.up = nn.UpsamplingBilinear2d(scale_factor=2)

        for param in self.parameters():
            param.requires_grad = False

    def forward(self, x):
        x = self.model(x)
        x = self.up(x)

        return x
```

**Comment by zxiangwei** [comment]
Sorry for the late reply. Thank you very much for your help, I executed the code  `self.model.load_state_dict(weight)`， but reported the following error:
![image](https://user-images.githubusercontent.com/44313751/149056872-2b43cc7b-fc87-4632-8921-684a3d247649.png)
![image](https://user-images.githubusercontent.com/44313751/149056931-82e46bcf-4431-410e-b025-f9ead36cc453.png)
How can I solve it please? thank you.

**Comment by SerialLain3170** [comment]
Do you use `resnet34` from [the link](https://github.com/RF5/danbooru-pretrained/blob/master/danbooru_resnet.py#L98)?
`model.load_state_dict` method works in my environment

**Comment by SerialLain3170** [comment]
Have you solved?

**Comment by zxiangwei** [comment]
Sorry, I haven't solved this problem yet. It's the same error reported last time. I want to confirm the problem of the environment again. My resnet34 is imported from the package torchvision.models, and then the weight file name I downloaded is resnet34-88a5e79d.pth. Are both of these correct?

**Comment by SerialLain3170** [comment]
The weigh file name your downloaded is correct. 

> My resnet34 is imported from the package torchvision.models

Strictly speaking, it is incorrect. My `resnet34` is imported from [this](https://github.com/RF5/danbooru-pretrained/blob/master/danbooru_resnet.py#L98). In the module, `torchvision.models.resnet34` is re-defined by [the function](https://github.com/RF5/danbooru-pretrained/blob/master/danbooru_resnet.py#L57). This can lead to changing keys in the weight file. Therefore, you need to import `resnet34` from [the module](https://github.com/RF5/danbooru-pretrained/blob/master/danbooru_resnet.py#L98).

**Comment by zxiangwei** [comment]
Thank you very much, after I changed to resnet34 as you said, the model loaded correctly. But when I selected the picture and clicked to color it, the following error appeared:
RuntimeError: The size of tensor a (127) must match the size of tensor b (128) at non-singleton dimension 2
The forward function in the class DownResBlock reports an error.
How can I solve it please? thank you.

**Comment by SerialLain3170** [comment]
The error seems to correspond to #25

> When it comes to the size mismatch error, the error comes from the limited shape that the point model can accept. At present, the point model can accept only shapes that are two to the Nth power (ex: 256, 512, 1024, etc). So, tentatively, you need to resize your images. 

I am sorry for the inconvenience. Tentatively, please follow that.

**Comment by zxiangwei** [comment]
Thank you very much for your help, I adjusted the pixels of the picture and now have the colorized result. Thanks again for your help.
