### ISSUE TITLE
How many epochs did you train your model for to obtain the result?

### ISSUE THREAD

**Issue by harrysdc** [SerialLain3170/Colorization#27]
Hi, your work is amazing!

I am wondering how many epochs did you train your model for to obtain your result? I tried to train your model for 100 epochs but the result is not as good as expected.

**Comment by SerialLain3170** [comment]
Thank you for the report!

Before I answer, what the model did you train and what the dataset do you use? And, what result did you got? 
In my opinion, regardless of the model, 100 epoch would be enough. I asked them for confirmation.

**Comment by harrysdc** [comment]
I trained nohint_pix2pix with [a dataset on Kaggle](https://www.kaggle.com/ktaebum/anime-sketch-colorization-pair). All of the result I obtained is bluish. I suspect it might be some issue related to pre-processing since I reuse your `class IllustDataset` and most of your code in `train.py` in my test script. But I have no clue how to Improve it. Any advice would be highly appreciated. Thank you:)
![133](https://user-images.githubusercontent.com/39647707/156953135-7535eb98-2571-4471-96b1-520028666f7c.png)
![203](https://user-images.githubusercontent.com/39647707/156953159-6c52e468-3813-4671-aa8b-71cbd472b381.png)

**Comment by SerialLain3170** [comment]
I think that the problem would be related to color space. Judging from the results, they are in BGR space. It depends on tools for saving image files (ex: OpenCV, Pillow). In both cases, you may be able to get the accurate results after you change color space into another color space (RGB->BGR, BGR->RGB).

**Comment by SerialLain3170** [comment]
Have you solved?
