### ISSUE TITLE
About stimulate in atari_userhint_v2/dataset.py

### ISSUE THREAD

**Issue by midsommar-2019** [SerialLain3170/Colorization#28]
I found your work very interesting and wanted to train with my own datasets.
But when I started train.py,  I came across an error 
ModuleNotFoundError: No module named 'stimulate'
Could you tell me how to get the module 'stimulate'?

Thank you

**Comment by SerialLain3170** [comment]
Thank you for the report! I am sorry for the late answer.

Since I forgot to push `stimulate.py`, I have pushed it just now. I am sorry for the inconvenience.

**Comment by midsommar-2019** [comment]
Thank you for the quick response! :) I could run it with my datasets.
