### ISSUE TITLE
would you mind share the training data of atari_userhint_v2? 

### ISSUE THREAD

**Issue by microfisher** [SerialLain3170/Colorization#29]
thanks for you job, your atari_userhint_v2 is fantastic!

**Comment by SerialLain3170** [comment]
Thank you for the issue!

I used [Tagged Anime Illustrations](https://www.kaggle.com/datasets/mylesoneill/tagged-anime-illustrations) for training the model. The alternative dataset is [Anime Sketch Colorization Pair](https://www.kaggle.com/datasets/ktaebum/anime-sketch-colorization-pair).

**Comment by microfisher** [comment]
> Thank you for the issue!
> 
> I used [Tagged Anime Illustrations](https://www.kaggle.com/datasets/mylesoneill/tagged-anime-illustrations) for training the model. The alternative dataset is [Anime Sketch Colorization Pair](https://www.kaggle.com/datasets/ktaebum/anime-sketch-colorization-pair).

thanks a lot!
