### ISSUE TITLE
How do you solve the u-net "lazy" problem?

### ISSUE THREAD

**Issue by fengchexz** [SerialLain3170/Colorization#3]
I notice that you don't use guide decoder,so how do you solve the u-net "lazy" problem?Can you help me? Thank you!

**Comment by SerialLain3170** [comment]
Sorry for the late answer. I noticed the Unet lazy problem in this [paper](https://arxiv.org/pdf/1706.03319.pdf). However, I succeeded to train my model without considering Unet lazy problem. In other worlds, I don't know how to solve the problem. I'm sorry not to answer your question fully. But, it may produce better quality to use guide decoder.
