### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by 252651980** [SerialLain3170/Colorization#30]
Hi, thanks for your resource, It's really fantastic!

I am a noob about python. I have some question about atari_userhint_v2:
1. What are SketchKeras and superpixel?
2. I noticed you used [Tagged Anime Illustrations](https://www.kaggle.com/datasets/mylesoneill/tagged-anime-illustrations) for training the model.  May I know how to use these pictures for DATA_PATH, SKETCH_PATH and SS_PATH?

Thanks.

**Comment by 252651980** [comment]
Another question. What is point_model.pt. Is it a training data? Where is the training data if point_model.pt is not in Adeleine.

**Comment by SerialLain3170** [comment]
Thank you for the issue. I will answer your question.

1. About SketchKeras and superpixel
    [SketchKeras](https://github.com/lllyasviel/sketchKeras): SketchKeras extracts line arts from colorized images. In order to train the line art colorization network, we need line arts as inputs of the network. Therefore, we have to employ line extraction methods for creating inputs, and SketchKeras is the reasonable one.
    superpixel: We can divide images into a lot of regions with superpixel algorithms like the figures on [the page](https://scikit-image.org/docs/dev/auto_examples/segmentation/plot_segmentations.html)

2. About `DATA_PATH`, `SKETCH_PATH` and `SS_PATH`
    Having done downloading Tagged Anime Illustrations, the path of the dataset corresponds to `DATA_PATH`. After this, you need to extract line arts from images in Tagged Anime Illustrations by SketchKeras, and the path containing line arts corresponds to `SKETCH_PATH`. As for `SS_PATH`, you can set `DATA_PATH` or `SKETCH_PATH` as `SS_PATH` because superpixel images in `SS_PATH` are not actually used in `atari_userhint_v2`. 

3. About `point_model.pt`
    `point_model.pt` is not the training data. It is the file containing weights of the trained model.

**Comment by 252651980** [comment]
> 

Thanks a lot for answering my questions. Where should I place the training data on Adeleine if it's ok from atari_userhint_v2.

**Comment by SerialLain3170** [comment]
I do not get the point. `Adeleine` is a GUI application that enables users to test their line arts. Training data is not needed on Adeleine, test data and the trained model file are needed.

**Comment by 252651980** [comment]
> I do not get the point. `Adeleine` is a GUI application that enables users to test their line arts. Training data is not needed on Adeleine, test data and the trained model file are needed.

I am sorry. My English is not that good. What I mean is how to associate [Adeleine](https://github.com/SerialLain3170/Colorization/tree/master/Adeleine) and [atari_userhint_v2](https://github.com/SerialLain3170/Colorization/tree/master/atari_userhint_v2)

**Comment by 252651980** [comment]
I should use [atari_userhint_v2](https://github.com/SerialLain3170/Colorization/tree/master/atari_userhint_v2) to train the data, which pictures downloaded, to get a file like print_model.pt. Then put it into the dir './Adeleine/ckpts/'. Is it right?

**Comment by SerialLain3170** [comment]
If you train your own model by using your own dataset, it is correct

**Comment by 252651980** [comment]
> 

Okay. Thanks a lot.
