### ISSUE TITLE
I couldn't get any data after training

### ISSUE THREAD

**Issue by 252651980** [SerialLain3170/Colorization#31]
Hi, I am sorry to trouble you again.  I didn't get any file like 'xxx.pt' after taining with [atari_userhint_v2](https://github.com/SerialLain3170/Colorization/tree/master/atari_userhint_v2). My command is 'python train.py --data_path images --sketch_path output --ss_path output'. The ymal params is:
![5e5a0cfc3ee1df2d6924a63d7e3d012](https://user-images.githubusercontent.com/16971362/163188519-74865489-121b-47be-95e1-9c479594534f.png).
There is not any data to get after training. Is there anything wrong with me? Thanks
![image](https://user-images.githubusercontent.com/16971362/163188731-db87701f-7e76-4d2f-9cdd-5f729e602f47.png)

**Comment by 252651980** [comment]
And [atari_userhint_v2](https://github.com/SerialLain3170/Colorization/tree/master/atari_userhint_v2) usually is out of memory when execute training. Would you please tell me how to solve the exception. Thanks

**Comment by SerialLain3170** [comment]
1. About not getting the model file
You need to set `snapshot_interval` lower than `epoch`. If you set `epoch` 2, I recommend that you set `snapshot_interval` 1.

2. About OOM
There are some methods for avoiding OOM on GPU. The easy solution is to decrease batch size.

**Comment by 252651980** [comment]
My GPU is Navida 1070gtx laptop version. It's still OOM when I set batch size 1. Would you please introduce the params about tarin. Thanks a lot.

**Comment by SerialLain3170** [comment]
I see. There are three options in `param.yaml` for decreasing the model size. 

- decrease `dataset.train_size`: 512 -> 256 or 128
- decrease `model.generator.num_layers`: 10 -> 4
- decrease `model.generator.up_layers`: [10, 5, 5, 3] -> [1, 1, 1, 1]

**Comment by 252651980** [comment]
> I see. There are three options in `param.yaml` for decreasing the model size.
> 
> * decrease `dataset.train_size`: 512 -> 256 or 128
> * decrease `model.generator.num_layers`: 10 -> 4
> * decrease `model.generator.up_layers`: [10, 5, 5, 3] -> [1, 1, 1, 1]

Okay. I will try. Thanks a lot again.
