### ISSUE TITLE
about scft

### ISSUE THREAD

**Issue by LHDLCV** [SerialLain3170/Colorization#36]
Hello, how many epochs have you trained in the SCFT project? And do you have a pre-trained model? Then how do you test the code? Looking forward to your reply.

**Comment by SerialLain3170** [comment]
Thank you for the issue and I am very sorry for the late answer.

I have trained SCFT model for 100 epochs, but less than 100 epochs may be enough. You can stop your training judging from the validation results (visualization results). I do not intend to upload the pre-trained model for SCFT.
