### ISSUE TITLE
Question about training atari_userhint_v2 with grayscale image

### ISSUE THREAD

**Issue by crodis-strife** [SerialLain3170/Colorization#37]
I'm developing a grayscale lineart colorization tool, generating the grayscale output image given lineart and grayscale hints.
When I tried to training atari_userhint_v2 with grayscale image, the error below occurs: 

![新點陣圖影像](https://user-images.githubusercontent.com/63531999/191562027-5f95e235-0178-48c2-a7fa-9586c8146e5c.jpg)

How can I fix this error? Thank you!

Also, this is the setup in param.yaml.

train:
    epoch: 1000
    snapshot_interval: 1000
    batchsize: 1
    validsize: 5
    out_guide: true
    gamma: 0.9

dataset:
    extension: ".jpg"
    train_size: 512
    valid_size: 512
    color_space: "gray"
    line_space: "gray"
    line_method: ["xdog", "pencil", "blend"]

model:
    generator:
        base: 64
        #in_ch: 5
        in_ch: 3
        lr: 0.0005
        b1: 0.0
        b2: 0.99
        guide: true
        resnext: true
        encoder_type: "res"
        num_layers: 10
        up_layers: [10, 5, 5, 3]
        #up_layers: [10, 5, 5, 1]
        mode: "train"
    discriminator:
        base: 64
        #in_ch: 3
        in_ch: 1
        multi: 1
        sn: false
        resnext: true
        patch: true
        lr: 0.0005
        b1: 0.0
        b2: 0.99
        mode: "train"
    vgg:
        mode: "eval"

loss:
    content: 1.0
    adv: 0.1
    tv: 100000.0
    pef: 0.01
    fm: 0.0
    perceptual: 100000.0
    gp: 1.0

**Comment by SerialLain3170** [comment]
Thank you for the issue, and I am very sorry for the late reply.

A generator of `atari_userhint_v2` is designed to output images that have 3 channels. To obtain grayscale output images, you need to change [the code](https://github.com/SerialLain3170/Colorization/blob/master/atari_userhint_v2/model.py#L640) into `EqualizedConv2d(base, 1, 3, 1, 1),`.

**Comment by crodis-strife** [comment]
Besides modifying EqualizedConv2d, I also made these modifications.

(1) loss.py
![loss_py](https://user-images.githubusercontent.com/63531999/193026685-1fc307c9-28a0-44f5-9521-c585000dde93.jpg)

(2) visualize.py
![visualize1](https://user-images.githubusercontent.com/63531999/193027752-6ae45d80-f7f2-42c3-b69e-7c97c6390103.jpg)
![visualize2](https://user-images.githubusercontent.com/63531999/193027778-6103bde3-a216-4dbb-9d42-e8b774de168e.jpg)

Now the training process runs properly.
![process](https://user-images.githubusercontent.com/63531999/193027463-48d127ff-21de-45b2-8f0e-62efe773c92f.jpg)

Thanks for your help!

**Comment by SerialLain3170** [comment]
I forgot that there are other places requiring 3 channels. Thank you!
