### ISSUE TITLE
The attn_type in param.yaml of reference_adain

### ISSUE THREAD

**Issue by humuhumu39** [SerialLain3170/Colorization#39]
Is the attn_type:"sa" in model.generator wrong option for training adain. I think it shoud be attn_type:"adain".
Am I wrong?

**Comment by humuhumu39** [comment]
oh, and how much GPU memory do you have?

I'm using RTX 3060 with 6GB memory.
When I'm training some models I always need to set batchsize very small,
like adain model I can only train in batchsize:2, train_size:256
and I even can NOT train scft model in batchsize:1, train_size:256.

It's sad, because I want to try scft model. ;(

**Comment by SerialLain3170** [comment]
I am very sorry for the late response.

> Is the attn_type:"sa" in model.generator wrong option for training adain. I think it shoud be attn_type:"adain".
Am I wrong?

You are right, and I am sorry for the confusion. 

> oh, and how much GPU memory do you have?

I trained my model with GPU whose memory is 24GB. If you would like to train SCFT model with RTX3060, I recommend that you decrease the `train_size` by changing 256 into 128.

**Comment by humuhumu39** [comment]
Thank you for replying!

I haven't trained adain model yet.
But the SCFT model, when I decrease the train_size to 128 that would cause a error.
It seems because instance_norm needs the Width and Height greater than 1, so eventually I upgraded my GPU to RTX3070 with 8GB memory, and train in batchsize: 1, train_size: 256.
Now I'm waiting the result, appreciate your help again. :)
