### ISSUE TITLE
Is the 'vedio' dir the code of the paper "Deep Line Art Video Colorization with a Few References"

### ISSUE THREAD

**Issue by int2char** [SerialLain3170/Colorization#4]
Is the 'vedio' dir the code of the paper "Deep Line Art Video Colorization with a Few References"?
when will the code be released ?

**Comment by SerialLain3170** [comment]
Sorry, I'm very busy. So the code will be released someday...
In fact, my implementation is based on this [paper](https://arxiv.org/pdf/2003.10685.pdf)

**Comment by int2char** [comment]
Thanks for your reply. I'm about to implement the paper, I was hesitant to wait for your code or implement the code by myself.  now I will try to implement the paper by myself and can I ask you for help if  there are some problems during my implementation ?

**Comment by SerialLain3170** [comment]
Of course, you can.
