### ISSUE TITLE
Do you mind sharing your pretrained no hint weights ?

### ISSUE THREAD

**Issue by ogkalu2** [SerialLain3170/Colorization#40]
Hi. Great work here. I was thing of integrating an automatic coloring tool with stable diffusion to sort of implement sketch-guided txt2img apart from google's paper and was wondering if you could release your no hint weights ?

**Comment by SerialLain3170** [comment]
I am sorry for the late reply. Unfortunately, I do not have models pre-trained without hints due to my mistake. Moreover, I recommend that you do not use my models for your purpose because my Pix2pix or Pix2pixHD models mostly produce single (black) colors on any regions except for faces.

**Comment by ogkalu2** [comment]
Oh Okay. Thanks for responding!
