### ISSUE TITLE
Prettained weights for "nohints" modes

### ISSUE THREAD

**Issue by Robolightning** [SerialLain3170/Colorization#41]
May anyone tell me please, is anywhere pre-trained weights for colorization in the "no hints" modes? In the repository, I only find scripts for training it, but the weights could not be found

**Comment by SerialLain3170** [comment]
Hi,

Thank you for the issue. As you said, the pre-trained model file for no hints modes is not here. Unfortunately, I also will not upload the file. I am sorry for not being your help.

**Comment by Robolightning** [comment]
> Hi,
> 
> Thank you for the issue. As you said, the pre-trained model file for no hints modes is not here. Unfortunately, I also will not upload the file. I am sorry for not being your help.

Hello, but maybe I can download it anywhere? Or not?

**Comment by SerialLain3170** [comment]
You would not be ale to download the model file from anywhere unless someone (not me) have uploaded.
