### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by SerialLain3170** [SerialLain3170/Colorization#6]
Source codes in this repository are hard to read and deal with (especially codes in pix2pixHD are terrible). So everything needs doing refactoring.  
Also, this repository blends Chainer and Pytorch as DNN framework. I would like to convert Chainer implementations into Pytorch implementations.

**Comment by gceboh** [comment]
[Awesome-Image-Colorization](https://github.com/MarkMoHR/Awesome-Image-Colorization), which contains a lot of source code, may be helpful.

**Comment by SerialLain3170** [comment]
Thanks! I think this may be very helpful.

**Comment by SerialLain3170** [comment]
I have replaced chainer implementation of pix2pix and pix2pix2HD with pytorch implementation
